version: '3.7'

services:
  db:
    container_name: ftvdev
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - PGDATA:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - ./database/database-data:/var/lib/postgresql/data

  visualizer:
    container_name: pgAdmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '8080:80'
    volumes:
      - ./database/pgadmin-data:/var/lib/pgadmin
    links:
      - 'database:pgsql-server'

  api:
    build: ./backend/api
    container_name: ftv_api
    restart: always
    volumes:
      - type: bind
        source: ./backend/api/
        target: /app
    working_dir: /app
    depends_on:
      - db
    expose:
      - 9000

  ui:
    build: ./frontend
    container_name: ftv_front
    restart: always
    volumes:
      - type: bind
        source: ./frontend/
        target: /app
    working_dir: /app
    expose:
      - 80

  nginx:
    build: ./backend/nginx
    container_name: ftv_nginx
    restart: always
    ports:
      - "8000:8000"
      - "8001:80"